/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Buy_House.java
 *
 * Created on Oct 25, 2018, 12:31:16 PM
 */
/**
 *
 * @author user
 */
public class Buy_House extends javax.swing.JFrame {

    /** Creates new form Buy_House */
    public Buy_House() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Pict1 = new javax.swing.JRadioButton();
        Pict2 = new javax.swing.JRadioButton();
        Pict3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        AksiaTimi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        Kefaleotxt = new javax.swing.JTextField();
        Epitokiotxt = new javax.swing.JTextField();
        Diarkiatxt = new javax.swing.JTextField();
        YpolDoseis = new javax.swing.JButton();
        Text1 = new javax.swing.JLabel();
        Doseis = new javax.swing.JLabel();
        alarm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Διαθέσημα Σπίτια"));

        buttonGroup1.add(Pict1);
        Pict1.setMnemonic('1');
        Pict1.setSelected(true);
        Pict1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Pict1.setBorderPainted(true);
        Pict1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatsworthHouse.jpg"))); // NOI18N
        Pict1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatsworthHousePressed.jpg"))); // NOI18N
        Pict1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatsworthHousePressed.jpg"))); // NOI18N
        Pict1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatsworthHousePressed.jpg"))); // NOI18N
        Pict1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Pict1ItemStateChanged(evt);
            }
        });
        Pict1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pict1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pict1MouseExited(evt);
            }
        });

        buttonGroup1.add(Pict2);
        Pict2.setMnemonic('2');
        Pict2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Pict2.setBorderPainted(true);
        Pict2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen_house.jpg"))); // NOI18N
        Pict2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/queen_housePressed.jpg"))); // NOI18N
        Pict2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/queen_housePressed.jpg"))); // NOI18N
        Pict2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/queen_housePressed.jpg"))); // NOI18N
        Pict2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Pict2ItemStateChanged(evt);
            }
        });
        Pict2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pict2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pict2MouseExited(evt);
            }
        });

        buttonGroup1.add(Pict3);
        Pict3.setMnemonic('3');
        Pict3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Pict3.setBorderPainted(true);
        Pict3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white_house.jpg"))); // NOI18N
        Pict3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/white_housePressed.jpg"))); // NOI18N
        Pict3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/white_housePressed.jpg"))); // NOI18N
        Pict3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/white_housePressed.jpg"))); // NOI18N
        Pict3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Pict3ItemStateChanged(evt);
            }
        });
        Pict3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pict3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pict3MouseExited(evt);
            }
        });

        jLabel1.setText("Αξία");

        AksiaTimi.setText("3.000.000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pict1)
                            .addComponent(Pict3)
                            .addComponent(Pict2))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AksiaTimi, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Pict1)
                .addGap(18, 18, 18)
                .addComponent(Pict2)
                .addGap(18, 18, 18)
                .addComponent(Pict3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AksiaTimi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Στοιχεία Δανίου"));
        jPanel2.setForeground(new java.awt.Color(0, 204, 255));
        jPanel2.setToolTipText("");

        jLabel2.setDisplayedMnemonic('K');
        jLabel2.setLabelFor(Kefaleotxt);
        jLabel2.setText("Κεφάλαιο:");
        jLabel2.setDisplayedMnemonicIndex(0);

        jLabel3.setDisplayedMnemonic('E');
        jLabel3.setLabelFor(Epitokiotxt);
        jLabel3.setText("Επιτόκιο:");
        jLabel3.setDisplayedMnemonicIndex(0);

        jLabel4.setDisplayedMnemonic('D');
        jLabel4.setLabelFor(Diarkiatxt);
        jLabel4.setText("Διάρκεια:");
        jLabel4.setDisplayedMnemonicIndex(0);

        Text2.setText("μήνες");

        Kefaleotxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Kefaleotxt.setText("0");

        Epitokiotxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Epitokiotxt.setText("0");
        Epitokiotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EpitokiotxtActionPerformed(evt);
            }
        });

        Diarkiatxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Diarkiatxt.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Kefaleotxt)
                    .addComponent(Epitokiotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(Diarkiatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(Text2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Kefaleotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Epitokiotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Diarkiatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text2))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        YpolDoseis.setMnemonic('Y');
        YpolDoseis.setText("Υπολογισμός Δόσης");
        YpolDoseis.setDisplayedMnemonicIndex(0);
        YpolDoseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YpolDoseisActionPerformed(evt);
            }
        });

        Text1.setText("Δόση ανα μήνα:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(YpolDoseis)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(Text1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Doseis, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(alarm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(YpolDoseis)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text1)
                            .addComponent(Doseis, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(alarm, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void Pict1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Pict1ItemStateChanged
    AksiaTimi.setText("3.000.000");
    price="3.000.000";
}//GEN-LAST:event_Pict1ItemStateChanged

private void Pict2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Pict2ItemStateChanged
    AksiaTimi.setText("5.000.000");
    price="5.000.000";
}//GEN-LAST:event_Pict2ItemStateChanged

private void Pict3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Pict3ItemStateChanged
    AksiaTimi.setText("4.000.000");
    price="4.000.000";
}//GEN-LAST:event_Pict3ItemStateChanged

private void Pict1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pict1MouseEntered
    AksiaTimi.setText("3.000.000");
    
}//GEN-LAST:event_Pict1MouseEntered

private void Pict1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pict1MouseExited
    AksiaTimi.setText(price);
}//GEN-LAST:event_Pict1MouseExited

private void Pict2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pict2MouseEntered
    AksiaTimi.setText("5.000.000");
}//GEN-LAST:event_Pict2MouseEntered

private void Pict2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pict2MouseExited
     AksiaTimi.setText(price);
}//GEN-LAST:event_Pict2MouseExited

private void Pict3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pict3MouseEntered
    AksiaTimi.setText("4.000.000");
}//GEN-LAST:event_Pict3MouseEntered

private void Pict3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pict3MouseExited
    AksiaTimi.setText(price);
}//GEN-LAST:event_Pict3MouseExited

private void YpolDoseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YpolDoseisActionPerformed
 //Αφαιρούμε τις dot απο τα ποσα π.χ. 3.000.000
 double kefaleoD=Double.valueOf(Kefaleotxt.getText().replace(".", "."))   ;
 double epitokioD=Double.valueOf(Epitokiotxt.getText().replace(".", "."))   ;
 double diarkeiaD=Double.valueOf(Diarkiatxt.getText().replace(".", "."))   ;
 double axiaD=Double.valueOf(price.replace(".", "."))   ;
 
 double daneio=axiaD-kefaleoD;
 if (daneio <= 0)
    alarm.setText("Δεν χρειάζεσαι δάνειο!");
 else{
     alarm.setText("");
     double tokos =(daneio*epitokioD)/100;
     double daneiometoko=daneio+tokos;
     if(diarkeiaD<=0)
         Doseis.setText("Λαθος διάρκεια");
     else{
         double dosi=daneiometoko/diarkeiaD;
         Doseis.setText(String.valueOf(dosi));
    }     
 } 
}//GEN-LAST:event_YpolDoseisActionPerformed

    private void EpitokiotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EpitokiotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EpitokiotxtActionPerformed

    String price = "3.000.000";
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
                
            public void run() {
                new Buy_House().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AksiaTimi;
    private javax.swing.JTextField Diarkiatxt;
    private javax.swing.JLabel Doseis;
    private javax.swing.JTextField Epitokiotxt;
    private javax.swing.JTextField Kefaleotxt;
    private javax.swing.JRadioButton Pict1;
    private javax.swing.JRadioButton Pict2;
    private javax.swing.JRadioButton Pict3;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JButton YpolDoseis;
    private javax.swing.JLabel alarm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
